#!/bin/bash

# - the "newest" syntax comes from point #87 of
#   https://catonmat.net/sed-one-liners-explained-part-three

_WINDOW_ID=0x5600049 # tigervnc boron
_WINDOW_ID=0x1400044 # tigervnc helium

# original (mine)
xprop -id $_WINDOW_ID | \
sed --expression='/^_NET_WM_NAME(UTF8_STRING) = /!d ; s/.* = //g'

# new (supposed to be faster than original)
xprop -id $_WINDOW_ID | \
sed --expression='/^_NET_WM_NAME(UTF8_STRING) = /!d ; /.* = / s///g'

# newest
xprop -id $_WINDOW_ID | \
sed --expression='/^_NET_WM_NAME(UTF8_STRING) = /!d ; s/// ; q'
